### PR TITLE
[Docs] add promote to preprod/prod steps

### PR DESCRIPTION
**Pull request by slallemand**

### CODE REVIEW

**Review by aureamunoz — APPROVED** [review]

**Comment by slallemand** [comment]
Don't merge it for now
I will add other steps : 
- stop DevSpaces Workspace at the end of each services deployment
- CVE detection in villain service

**Comment by slallemand** [comment]
Ready ; can be reviewed and merged

**Comment by aureamunoz** [comment]
Does this PR include the CVE dependency? Does it supersede the #129 one? @slallemand @ozangunalp

**Comment by slallemand** [comment]
@aureamunoz Yes, the documentation regarding the CVE is in the doc (docs/docs/villain-microservice.md)

**Comment by aureamunoz** [comment]
> @aureamunoz Yes, the documentation regarding the CVE is in the doc (docs/docs/villain-microservice.md)

ok, I will close the #129 then.

**Pull request merged**
