### PR TITLE
Introduce dependency containing a CVE to the villain service

### PR DESCRIPTION
**Pull request by ozangunalp**

### CODE REVIEW

**Review by aureamunoz — COMMENTED** [review]
The [RH Trusted pipelines](https://cescoffier.github.io/quarkus-openshift-workshop/trusted-apps/ )needs to be reviewed and aligned with this?

**Review by cescoffier — APPROVED** [review]

**Comment by slallemand** [comment]
Just did a quick test introducing this CVE 
Quay scanner is ok and see the critical CVE ... but ... ACS don't see anything ... I'm checking what could be wrong (hope it's on my side and not ACS)

**Comment by ozangunalp** [comment]
@aureamunoz 
> The [RH Trusted pipelines](https://cescoffier.github.io/quarkus-openshift-workshop/trusted-apps/) needs to be reviewed and aligned with this?

I think we can add a section to the villain service to detect and correct the cve. But we need to make sure that ACS is detecting it.

**Comment by slallemand** [comment]
I have added this dependency in my RHDH templates and my pipeline is now able to catch
Documentation has been updated too (PR in review for now).

Btw, unsure it's needed to introduce the dependency here (this code is note in use in the Workshop).

**Comment by aureamunoz** [comment]
Superseded by #137

**Pull request closed without merging**
